<?php

namespace DMH\ECommerceBundle\Repository;

/**
 * CostumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostumeRepository extends \Doctrine\ORM\EntityRepository
{
}
