product:
    type:     rest
    resource: DMH\ECommerceBundle\Controller\Rest\ProductController
    name_prefix:  api_

product_model:
    type:     rest
    parent: product
    resource: DMH\ECommerceBundle\Controller\Rest\ProductModelController
    name_prefix:  api_

product_thumbnail:
    type:     rest
    parent: product
    resource: DMH\ECommerceBundle\Controller\Rest\ProductThumbnailController
    name_prefix:  api_

costume:
    type:     rest
    resource: DMH\ECommerceBundle\Controller\Rest\CostumeController
    name_prefix:  api_

category:
    type:     rest
    resource: DMH\ECommerceBundle\Controller\Rest\CategoryController
    name_prefix:  api_

universe:
    type:     rest
    resource: DMH\ECommerceBundle\Controller\Rest\UniverseController
    name_prefix:  api_

creation:
    type:     rest
    resource: DMH\ECommerceBundle\Controller\Rest\CreationController
    name_prefix:  api_

basket:
    type:     rest
    resource: DMH\ECommerceBundle\Controller\Rest\BasketController
    name_prefix:  api_