services:
#    dmhe_commerce.example:
#        class: DMH\ECommerceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    dmh_ecommerce.doctrine_listener.product:
        class: DMH\ECommerceBundle\DoctrineListener\ProductListener
        arguments: []
        tags:
          - { name: doctrine.event_listener, event: postPersist }
