services:
#    dmhe_commerce.example:
#        class: DMH\ECommerceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    dmh_ecommerce.doctrine_listener.product:
        class: DMH\ECommerceBundle\DoctrineListener\ProductListener
        arguments: []
        tags:
          - { name: doctrine.event_listener, event: postPersist }

    dmh_ecommerce.doctrine_listener.universe.post_persist:
        class: DMH\ECommerceBundle\DoctrineListener\UniverseCreationListener
        arguments: []
        tags:
          - { name: doctrine.event_listener, event: postPersist }

#    dmh_ecommerce.doctrine_listener.product.pre_delete:
#        class: DMH\ECommerceBundle\DoctrineListener\ProductRemoveListener
#        arguments: []
#        tags:
#          - { name: doctrine.event_listener, event: preRemove }
#
#    dmh_ecommerce.doctrine_listener.product.post_delete:
#            class: DMH\ECommerceBundle\DoctrineListener\ProductRemoveListener
#            arguments: []
#            tags:
#              - { name: doctrine.event_listener, event: postRemove }

    dmh_ecommerce.product.directory_remover:
        class: DMH\ECommerceBundle\DoctrineListener\ProductRemoveListener
